---

# This role is to set up a stand-alone environment for the Migration process

  classes:
    - profiles::mongodb
    - profiles::nginx
    - profiles::postgresql
    - profiles::rabbitmq
    - profiles::appserver
    - profiles::geos_addins

  # Temporary workaround due to PIP using different configuration folder to RPM
  profiles::appserver::supervisor_conf:
    - /etc/supervisord.d/*.ini
    - /etc/supervisor.d/*.conf

  postgres_databases:
    systemofrecord:
      user: systemofrecord
      password: md511c5a6395e27555ef43eb7b05c76d7c1
      owner: systemofrecord
    verification:
      user: verification
      password: md51f9f5bb065dcc48f72ec3e7c4de17e33
      owner: verification

  postgres_users:
    deployment:
      password_hash: md5dddbab2fa26c65fadeaa8b1076329a14

  rabbitmq_users:
    rabbitmqadmin:
      admin: true
      password: 'rabbitmqadminrabbitmqadmin'

  rabbitmq_user_permissions:
    rabbitmqadmin@/:
      configure_permission: '.*'
      read_permission: '.*'
      write_permission: '.*'

  rabbitmq:
    delete_guest_user: true
