---

classes:
  - 'profiles::appserver'
  - 'profiles::rabbitmq'

rabbitmq_users:
  rabbitmqadmin:
    admin: true
    password: 'rabbitmqadminrabbitmqadmin'

rabbitmq_user_permissions:
  rabbitmqadmin@/:
    configure_permission: '.*'
    read_permission: '.*'
    write_permission: '.*'

rabbitmq:
  delete_guest_user: true
