---

classes:
  - profiles::appserver
  - profiles::postgresql
  - profiles::rabbitmq

postgres_databases:
  systemofrecord:
    user: systemofrecord
    password: md511c5a6395e27555ef43eb7b05c76d7c1
    owner: systemofrecord
  audit:
    user: audit
    password: md59b17b5b73604c92182a4575ab96f4be8
    owner: audit

postgres_users:
  deployment:
    password_hash: md5dddbab2fa26c65fadeaa8b1076329a14

rabbitmq_users:
  rabbitmqadmin:
    admin: true
    password: 'rabbitmqadminrabbitmqadmin'

rabbitmq_user_permissions:
  rabbitmqadmin@/:
    configure_permission: '.*'
    read_permission: '.*'
    write_permission: '.*'

rabbitmq:
  delete_guest_user: true
